In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import make_blobs
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [2]:
X, y = make_blobs(100, 2, centers=2, random_state=2, cluster_std=1.5)
plt.scatter(X[:, 0], X[:, 1], c=y, s=50, cmap='coolwarm');
plt.show()

In [3]:
model = GaussianNB()
model.fit(X, y);

In [4]:
rng = np.random.RandomState(0)
Xnouv = [-4, -16] + [12, 20] * rng.rand(3000, 2)
ynouv = model.predict(Xnouv)

In [5]:
plt.scatter(X[:, 0], X[:, 1], c=y, s=50, cmap='coolwarm')
lim = plt.axis()
plt.scatter(Xnouv[:, 0], Xnouv[:, 1], c=ynouv, s=20, cmap='coolwarm', alpha=0.1)
plt.axis(lim);

In [6]:
import pandas as pd
Iris=pd.read_pickle('iris.pkl')

In [7]:
Iris.head()

sépale_longueur  sépale_largeur  pétale_longueur  pétale_largeur  espèce
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x=Iris.iloc[:,:-1]#longeur et largeur des sepales
y=Iris.iloc[:,4]#etiquette espece
x_a,x_test, y_a, y_test=train_test_split(x,y,test_size=0.10)

In [10]:
model.fit(x_a, y_a);#apprentiassage
prédictions = model.predict(x_test)#prediction

In [11]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

In [12]:
print(metrics.classification_report(y_test, prédictions))
print(metrics.confusion_matrix(y_test, prédictions))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         4
  versicolor       1.00      1.00      1.00         3
   virginica       1.00      1.00      1.00         8

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

[[4 0 0]
 [0 3 0]
 [0 0 8]]
