In [1]:
import numpy as np

In [2]:
ar = np.array([1,2,3,4])

In [4]:
ar.dtype

dtype('int32')

In [5]:
print("dimension=",ar.ndim,"taille=",ar.size, "forme=", ar.shape)#ndim= dimension /size=taille/ shape= forme obtenue

dimension= 1 taille= 4 forme= (4,)


In [6]:
ar[1]

2

In [7]:
print("ar[-1]=", ar[-1], "et ar[-2]=", ar[-2]) # regarder les valeurs  a partir de la fin

ar[-1]= 4 et ar[-2]= 3


In [16]:
ar1 = np.array([[1,2,3],[4,5,6]])

In [17]:
ar1[1,0]

4

In [18]:
ar1[0,0]=7

In [19]:
ar1[1,2]=np.pi

In [20]:
ar1#garde que la valeur entiere car tab avec un seul type

array([[7, 2, 3],
       [4, 5, 3]])

In [21]:
ar2 = np.arange(0,20,3)
ar2

array([ 0,  3,  6,  9, 12, 15, 18])

In [22]:
ar3 = ar2[:5] #contient les 5 premiers elem de ar2

In [23]:
ar3

array([ 0,  3,  6,  9, 12])

In [24]:
ar3 = ar2[:4:2]

In [25]:
ar3

array([0, 6])

In [26]:
ar3[3::-1] #on va jusqu'à l'indice 3 et on inverse le tableau

array([6, 0])

In [27]:
ar1.shape

(2, 3)

In [28]:
ar4 = ar1.reshape(3, 2)#affect tab remodler à ar4

In [29]:
ar4

array([[7, 2],
       [3, 4],
       [5, 3]])